import Head from 'next/head';
import Editor from '@/features/Editor/Editor';
import { useEffect, useState } from 'react';
import { Box } from '@/components';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setIsLoading(false);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {isLoading && <div>Loading...</div>}
        {!isLoading && (
          <Box>
            <Editor />
          </Box>
        )}
      </main>
    </>
  );
}
